default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: saneigen
  password: saneigen
  host: localhost

development:
  <<: *default
  database: lambnote_development

test:
  <<: *default
  database: lambnote_test

production:
  <<: *default
  database: lambnote_production
  username: lambnote
  password: <%= ENV['LAMBNOTE_DATABASE_PASSWORD'] %>
